M48
; DRILL file {KiCad 7.0.6} date Mon Jul 10 12:59:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-10T12:59:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X7.2884Y-3.2537
X7.2884Y-3.3037
X7.2884Y-3.3537
X7.2884Y-3.4037
X7.2884Y-3.4537
T0
M30
